server:
  port: ${APP_PORT:9090}
  servlet:
    context-path: /addressbook
  compression:
    enabled: true
    min-response-size: 1024
  forward-headers-strategy: framework

spring:
  banner:
    location: classpath:banner.txt
  profiles:
    active: ${PROFILE:local,dev}
  jpa:
    database: POSTGRESQL
    show-sql: true
    hibernate:
      ddl-auto: create
  datasource:
    platform: postgres
    url: jdbc:postgresql://${DATABASE_HOST:localhost}:${DATABASE_PORT:5432}/${DATABASE_NAME:addressbook}
    username: ${DATABASE_USER:root}
    password: ${DATABASE_PASSWORD:root}
    driverClassName: org.postgresql.Driver
  flyway:
    enabled: true
    baselineOnMigrate: true
    validateOnMigrate: true
    locations: classpath:db/migration

management:
  endpoints:
    web:
      exposure:
        include: "*"
  endpoint:
    health:
      show-details: always

application:
  configuration:
    cors-allowed-list:
      - http://localhost:6555
      - ${PORTAL_URL:http://localhost:8080}
      - ${API_URL:http://localhost:9090}
    public-api-list:
      - /api/public/**

logging:
  pattern:
    console: "%d{dd-MM-yyyy HH:mm:ss.SSS} %thread ${PID} [%X{correlationId}] %-5level %logger{36} - %class{1} - %msg%n"