kind: Deployment
apiVersion: apps/v1
metadata:
  name: addressbook
spec:
  replicas: 1
  selector:
    matchLabels:
      app: addressbook
  template:
    metadata:
      labels:
        app: addressbook
    spec:
      containers:
        - name: addressbook-cont
          image: nexus.local:5000/java-school/cloud/addressbook:1